---
- import_role:
    name: docker_service
  vars:
    docker_service_name: mariadb
    docker_service_image_name: "{{ mariadb_image_name }}"
    docker_service_mount_points:
    - path: "{{ mariadb_config_dir }}"

# Kodi database does not need to be secure.
- name: Create a MariaDB user for Kodi
  mysql_user:
    name: kodi
    host: '%'
    password: kodi
    priv: '*.*:ALL'
    check_implicit_admin: yes
  # XXX Client connections are flaky immediately after a restart.
  #     Perhaps an issue with the linuxserver/mariadb image?
  #     Tried waiting for the host port to open, but still flaky.
  #     So resorting to delayed retries.  Seems to work.
  retries: 3
  delay: 3
  register: mariadb_user
  until: mariadb_user is not failed
