#!/usr/bin/env -S ansible-playbook --ask-become-pass
---
#
# Proxies access to services behind Red Hat's corporate VPN.
#

- name: Configure CSB host to proxy services
  hosts: csb.home.arpa

  roles:

    - role: fedora_csb_proxy
