#!/usr/bin/env -S ansible-playbook --ask-become-pass
---
#
# Configures hosts in an inventory group named "development_group"
# consisting of pre-installed Debian GNU/Linux hosts with networking
# and SSH service available, and the remote user in the "sudo" group.
#
# Usage: ./development.yml [--limit HOSTS] [--tags TAGS]
#
# Available tags:
# - system        : Run all system-level tasks (as root)
# - user          : Run all user-level tasks
# - common_system : (system) Common System Configuration
# - dropbox       : (system) Dropbox Configuration
# - redhat        : (system) Red Hat Configuration
# - common_user   : (user) Common User Configuration
# - deb_maint     : (user) Debian Maintainer Configuration
# - powerline     : (user) Powerline Configuration
# - golang        : (user) Golang Configuration
#

- name: Configure hosts for a Red Hat development environment
  hosts: development_group

  vars:
    # Necessary for the secrets role because the password store repo is private.
    ansible_ssh_common_args: -o ForwardAgent=yes

    git_dev_user_email: mbarnes@fedorapeople.org
    git_dev_user_signingkey: 612E87B275813A59

  pre_tasks:

    - name: Check for necessary inventory variables
      ansible.builtin.assert:
        that: "item is defined"
        msg: "Missing required variable \"{{ item }}\". Please add this to your inventory."
      loop:
        - local_area_network
        - local_area_netmask
      tags:
        - always

  roles:

    # -----------------------------
    #  Common System Configuration
    # -----------------------------

    - role: common_system
      vars:
        common_system_extra_packages:
          - systemd-resolved
      tags:
        - common_system
        - system

    # -----------------------
    #  Dropbox Configuration
    # -----------------------

    # FIXME Package is obsolete; re-evaluate whether to keep.
    # - role: dropbox
    #   tags:
    #     - dropbox
    #     - system

    # -----------------------
    #  Red Hat Configuration
    # -----------------------

    - role: redhat
      tags:
        - redhat
        - system

    - role: redhat_aro
      tags:
        - redhat
        - system

    # ---------------------------
    #  Common User Configuration
    # ---------------------------

    - role: common_user
      tags:
        - common_user
        - user

    # ---------------------------------
    #  Debian Maintainer Configuration
    # ---------------------------------

    - role: deb_maint
      vars:
        deb_maint_email: mbarnes@fastmail.com
      tags:
        - deb_maint
        - user

    # -------------------------
    #  Powerline Configuration
    # -------------------------

    - role: powerline
      tags:
        - powerline
        - user

    # ----------------------
    #  Golang Configuration
    # ----------------------

    - role: golang
      tags:
        - golang
        - user

  tasks:

    - name: List manual follow-up tasks
      ansible.builtin.pause:
        prompt: |

          Additional tasks out of scope for this playbook:

            [ ] Sign in to Firefox account
            [ ] Configure Firefox to use RH Kerberos ticket:
                - about:config
                - network.negotiate-auth.trusted-uris = .redhat.com

        seconds: 1
      tags:
        - user
