#!/usr/bin/ansible-playbook
---
#
# Configures hosts in an inventory group named "development_group"
# consisting of pre-installed Debian GNU/Linux hosts with networking
# and SSH service available, and the remote user in the "sudo" group.
#
# Usage: ./development.yml --ask-become-pass
#
# Available tags:
# - system        : Run all system-level tasks (as root)
# - user          : Run all user-level tasks
# - common_system : (system) Common System Configuration
# - dropbox       : (system) Dropbox Configuration
# - google_chrome : (system) Google Chrome Configuration
# - redhat        : (system) Red Hat Configuration
# - common_user   : (user) Common User Configuration
# - deb_maint     : (user) Debian Maintainer Configuration
# - powerline     : (user) Powerline Configuration
# - golang        : (user) Golang Configuration
#

- hosts: development_group

  vars:
    git_config_user_email: mbarnes@fedorapeople.org
    git_config_user_signingkey: 612E87B275813A59

  pre_tasks:

  - name: Check for necessary inventory variables
    assert:
      that: "item is defined"
      msg: "Missing required variable \"{{ item }}\". Please add this to your inventory."
    loop:
    - local_area_network
    - local_area_netmask
    tags:
    - always

  tasks:

  #-----------------------------
  # Common System Configuration
  #-----------------------------

  - import_role:
      name: common_system
    vars:
      common_system_extra_packages:
      - systemd-resolved
    tags:
    - common_system
    - system

  #-----------------------
  # Dropbox Configuration
  #-----------------------

  # FIXME Package is obsolete; re-evaluate whether to keep.
  #- import_role:
  #    name: dropbox
  #  tags:
  #  - dropbox
  #  - system

  #-----------------------------
  # Google Chrome Configuration
  #-----------------------------

  # FIXME Re-evaluate whether Google Meet works well on Firefox.
  #       If it does, maybe we don't need Chrome?
  #- import_role:
  #    name: google_chrome
  #  tags:
  #  - google_chrome
  #  - system

  #-----------------------
  # Red Hat Configuration
  #-----------------------

  - import_role:
      name: redhat
    tags:
    - redhat
    - system

  - import_role:
      name: redhat_aro
    tags:
    - redhat
    - system

  #---------------------------
  # Common User Configuration
  #---------------------------

  - import_role:
      name: common_user
    tags:
    - common_user
    - user

  #---------------------------------
  # Debian Maintainer Configuration
  #---------------------------------

  - import_role:
      name: deb_maint
    vars:
      deb_email: mbarnes@fastmail.com
    tags:
    - deb_maint
    - user

  #-------------------------
  # Powerline Configuration
  #-------------------------

  - import_role:
      name: powerline
    tags:
    - powerline
    - user

  #----------------------
  # Golang Configuration
  #----------------------

  - import_role:
      name: golang
    tags:
    - golang
    - user

