#!/usr/bin/env -S ansible-playbook
---
#
# Configures hosts in an inventory group named "mediacenter_group"
# consisting of pre-installed OSMC devices with networking and SSH
# service available.
#
# Usage: ./mediacenter.yml [--limit HOSTS] [--tags TAGS]
#
# Available tags:
# - system        : Run all system-level tasks (as root)
# - user          : Run all user-level tasks
# - common_system : (system) Common System Configuration
# - journal       : (system) Journal Configuration
# - connman       : (system) ConnMan Configuration
# - mta           : (system) Mail Transfer Agent (MTA) Configuration
# - ups           : (system) Uninterruptible Power Supply (UPS) Configuration
# - common_user   : (user) Common User Configuration
# - powerline     : (user) Powerline Configuration
# - retropie      : (user) RetroPie Configuration
#

- name: Configure hosts to run Open Source Media Center (OSMC)
  hosts: mediacenter_group
  remote_user: osmc

  pre_tasks:

    - name: Check Ansible version
      ansible.builtin.assert:
        that: "ansible_version.full is version('2.9', '>=')"
        msg: "This playbook requires Ansible 2.9 or later"
      tags:
        - always

    - name: Check for necessary inventory variables
      ansible.builtin.assert:
        that: "item is defined"
        msg: "Missing required variable \"{{ item }}\". Please add this to your inventory."
      loop:
        - local_area_network
        - local_area_netmask
      tags:
        - always

  roles:

    # -----------------------------
    #  Common System Configuration
    # -----------------------------

    - role: common_system
      vars:
        common_system_extra_packages:
          - python3-netaddr  # for ipaddr filter
      tags:
        - common_system
        - system

    # -----------------------
    #  Journal Configuration
    # -----------------------

    - role: journal
      tags:
        - journal
        - system

    # -----------------------
    #  ConnMan Configuration
    # -----------------------

    - role: connman
      tags:
        - connman
        - system

    # ---------------------------
    #  Common User Configuration
    # ---------------------------

    - role: common_user
      tags:
        - common_user
        - user

    # -------------------------
    #  Powerline Configuration
    # -------------------------

    - role: powerline
      tags:
        - powerline
        - user

    # ------------------------
    #  RetroPie Configuration
    # ------------------------

    - role: retropie
      tags:
        - retropie
        - user
