---
- name: Begin Docker configuration
  become: yes
  block:

  - name: Add Docker's official GPG key
    get_url:
      url: https://download.docker.com/linux/debian/gpg
      dest: /etc/apt/trusted.gpg.d/docker.asc

  - name: Add apt repository for Docker
    apt_repository:
      repo: "deb https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
      filename: docker

  # XXX Workaround for Docker on Debian Bullseye
  #     (Is this still needed on Debian Bookworm?)
  #     https://github.com/moby/libnetwork/issues/2331
  - name: Add iptables package
    apt:
      name:
      - iptables

  - name: Link iptables to iptables-legacy
    command: update-alternatives --set iptables /usr/sbin/iptables-legacy

  - name: Add docker-ce packages
    apt:
      name:
      - docker-ce
      - docker-ce-cli

  - name: Add user to "docker" group
    user:
      name: "{{ ansible_user_id }}"
      groups: docker
      append: yes

  - name: Enable and start docker.service
    systemd:
      name: docker.service
      enabled: yes
      state: started
