---
- import_role:
    name: docker_service
  vars:
    docker_service_name: nzbget
    docker_service_image_name: "{{ nzbget_image_name }}"
    docker_service_mount_points:
    - path: "{{ nzbget_config_dir }}"
    docker_service_config_tasks: "../nzbget/tasks/nzbget_config_tasks.yml"
    docker_service_environment: |
      CONTAINER_MEMORY_LIMIT={{ nzbget_memory_limit }}

- import_role:
    name: nginx_revproxy
  vars:
    nginx_revproxy_name: nzbget
    nginx_revproxy_port: "{{ nzbget_host_port }}"
