---
- name: Begin Google Cloud SDK configuration
  become: true
  block:

    - name: Add apt repository for Google Cloud SDK
      ansible.builtin.deb822_repository:
        name: google-cloud-sdk
        architectures: "{{ dpkg_architecture }}"
        uris: https://packages.cloud.google.com/apt
        suites: cloud-sdk
        components: main
        signed_by: https://packages.cloud.google.com/apt/doc/apt-key.gpg

    - name: Remove old system-wide GPG key for Google Cloud SDK
      ansible.builtin.file:
        path: "{{ google_cloud_sdk_signing_key_path }}"
        state: absent

    - name: Remove old-style apt repository for Google Cloud SDK
      ansible.builtin.file:
        path: /etc/apt/sources.list.d/google-cloud-sdk.list
        state: absent

    - name: Add google-cloud-cli package
      ansible.builtin.apt:
        name:
          - google-cloud-cli
        update_cache: true
