---
- import_role:
    name: github_release
  vars:
    github_release_name: Git Credential Manager
    github_release_owner: git-ecosystem
    github_release_repo: git-credential-manager

- name: Add bash configuration
  copy:
    src: git-credential-manager
    dest: "{{ bash_aliases_dir }}/"
