---
- import_role:
    name: docker_service
  vars:
    docker_service_name: pihole
    docker_service_image_name: "{{ pihole_image_name }}"
    docker_service_mount_points:
    - path: /etc/pihole
      # These are the UID and GID used in the container.
      # Consider overriding with PIHOLE_UID and PIHOLE_GID?
      owner: 999
      group: 1000
    - path: /etc/dnsmasq.d
      owner: root
      group: root
    docker_service_config_tasks: "../pihole/tasks/pihole_config_tasks.yml"
    docker_service_environment: |
      CONTAINER_MEMORY_LIMIT={{ pihole_memory_limit }}

- import_role:
    name: nginx_revproxy
  vars:
    nginx_revproxy_name: pihole
    nginx_revproxy_port: "{{ pihole_host_http_port }}"
  when: pihole_host_http_port != 80
