---
- name: Begin Red Hat ARO configuration
  become: true
  block:

    # From https://packages.microsoft.com/keys/README (edited for brevity)
    #
    # Starting in the Spring of 2025, packages.microsoft.com is introducing
    # a new signing key for some repositories. The existing key (BE1229CF)
    # includes SHA1 signatures. These were commonplace when that key was
    # created, but support for SHA1 (and keys that use it) has been deprecated
    # in recent Linux releases. The introduction of this new signing key
    # represents our effort to keep pace with evolving security standards,
    # and ensure users of these new Linux releases can continue to be
    # supported by packages.microsoft.com.
    #
    # A brief description of the keys used on packages.microsoft.com:
    #
    # microsoft.asc (BC528686B50D79E339D3721CEB3E94ADBE1229CF):
    # This key was Microsoft’s standard Linux-signing key until Spring 2025, as
    # discussed above. This key will not be used for newly-created repositories.
    #
    # microsoft-2025.asc (AA86F75E427A19DD33346403EE4D7792F748182B):
    # This is the current standard Linux-signing key that will be used in newly-
    # created repositories. It will work properly in distributions that disallow
    # SHA1 signatures.
    #
    # microsoft-rolling.asc:
    # This is currently a copy of microsoft-2025.asc. The intention is that this
    # file will be updated in the future to include new keys as they are created
    # and begin being used.

    - name: Add Microsoft's legacy GPG key
      ansible.builtin.get_url:
        url: https://packages.microsoft.com/keys/microsoft.asc
        dest: "{{ redhat_aro_microsoft_legacy_signing_key_path }}"
        mode: u=rw,g=r,o=r

    - name: Add Microsoft's rolling GPG key
      ansible.builtin.get_url:
        url: https://packages.microsoft.com/keys/microsoft-rolling.asc
        dest: "{{ redhat_aro_microsoft_rolling_signing_key_path }}"
        mode: u=rw,g=r,o=r
        force: true  # in case there's new keys

    # azure-cli releases are notoriously slow and may not be available for the
    # current distribution release ("ansible_distribution_release"). This fact
    # provides a clean way to temporarily override.
    - name: Set Debian release for Azure CLI
      ansible.builtin.set_fact:
        redhat_aro_azure_cli_distribution_release: "bookworm"
      when: ansible_distribution == 'Debian'

    - name: Set Ubuntu release for Azure CLI
      ansible.builtin.set_fact:
        redhat_aro_azure_cli_distribution_release: "noble"
      when: ansible_distribution == 'Ubuntu'

    - name: Add apt repository for Azure CLI
      ansible.builtin.apt_repository:
        repo: >
          deb [arch={{ dpkg_architecture }} signed-by={{ redhat_aro_microsoft_legacy_signing_key_path }}]
          https://packages.microsoft.com/repos/azure-cli/ {{ redhat_aro_azure_cli_distribution_release }} main
        filename: azure-cli

    - name: Add packages for ARO development
      ansible.builtin.apt:
        name:
          - azure-cli
          - curl
          - jq
          - make
          - net-tools
          - podman
          - virt-viewer

    - name: Add packages for ARO development (Debian-only)
      ansible.builtin.apt:
        name:
          - npm
          - promtool
      when: ansible_distribution == 'Debian'

    - name: Add packages for ARO development (Ubuntu-only)
      ansible.builtin.apt:
        name:
          # We are currently stuck on an old Ubuntu release (24.04) for Intune
          # compliance and therefore have to employ some package workarounds:
          #
          # - npm package is too old for our purposes. I have instead installed
          #   npm directly from https://github.com/nodesource and am not going
          #   to bother trying to automate that with Ansible.
          # - promtool is not available as a standalone package. Need to install
          #   the full prometheus package instead.
          - prometheus
      when: ansible_distribution == 'Ubuntu'

- name: Add bash aliases
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ common_user_bash_aliases_dir }}/"
    mode: u=rw,g=rw,o=r
  loop:
    - aro_hcp
    - aro_hcp_testing

- name: Install Azure Bicep CLI
  ansible.builtin.command:
    cmd: az bicep install
    creates: "{{ ansible_user_dir }}/.azure/bin/bicep"
  register: azure_bicep_installed

- name: Update Azure Bicep CLI
  ansible.builtin.command:
    cmd: az bicep upgrade
  when: not azure_bicep_installed.changed

- name: Install kubectl
  ansible.builtin.command:
    cmd: >
      az aks install-cli
      --install-location {{ ansible_user_dir }}/.local/bin/kubectl
      --kubelogin-install-location {{ ansible_user_dir }}/.local/bin/kubelogin
    creates: "{{ ansible_user_dir }}/.local/bin/kubectl"

- name: Install the latest ocm-cli release
  ansible.builtin.import_role:
    name: github_release
  vars:
    github_release_owner: openshift-online
    github_release_repo: ocm-cli
    github_release_binary_name: ocm

- name: Configure host for Microsoft Intune
  ansible.builtin.include_tasks: microsoft_intune.yml
  when: enable_microsoft_intune | default(False)

- name: Add bash command for exporting Microsoft's YubiKey
  ansible.builtin.template:
    src: yubikey_export.j2
    dest: "{{ common_user_bash_aliases_dir }}/yubikey_export"
    mode: u=rw,g=rw,o=r
  when: usbip_server | default(False)

- name: Add bash command for remotely attaching Microsoft's YubiKey
  ansible.builtin.template:
    src: yubikey_attach.j2
    dest: "{{ common_user_bash_aliases_dir }}/yubikey_attach"
    mode: u=rw,g=rw,o=r
  when: usbip_client | default(False)
