---
- name: Begin Microsoft Intune configuration
  become: true
  block:

    # Note: Microsoft Intune also requires the operating system be
    #       installed on an encrypted volume but that's beyond the
    #       scope of this playbook.

    - name: Add pwquality PAM module
      ansible.builtin.apt:
        name: libpam-pwquality

    - name: Configure pwquality to meet Microsoft Intune requirements
      community.general.pamd:
        name: common-password
        type: password
        control: requisite
        module_path: pam_pwquality.so
        module_arguments:
          - minlen=12
          - dcredit=-1
          - ucredit=-1
          - lcredit=-1
          - ocredit=-1
        state: args_present

    - name: Add Microsoft's main apt repository for Ubuntu
      ansible.builtin.deb822_repository:
        name: "microsoft-{{ ansible_distribution | lower }}-{{ ansible_distribution_release }}-prod"
        architectures: "{{ dpkg_architecture }}"
        uris: "https://packages.microsoft.com/{{ ansible_distribution | lower }}/{{ ansible_distribution_version }}/prod"
        suites: "{{ ansible_distribution_release }}"
        components: main
        signed_by: "{{ redhat_aro_microsoft_legacy_signing_key_path }}"

    - name: Remove old-style main apt repository for Ubuntu
      ansible.builtin.file:
        path: "/etc/apt/sources.list.d/microsoft-{{ ansible_distribution | lower }}-{{ ansible_distribution_release }}-prod.list"
        state: absent

    - name: Add Microsoft's "insiders fast" apt repository for Ubuntu
      ansible.builtin.deb822_repository:
        name: "microsoft-{{ ansible_distribution | lower }}-{{ ansible_distribution_release }}-insiders-fast"
        architectures: "{{ dpkg_architecture }}"
        uris: "https://packages.microsoft.com/{{ ansible_distribution | lower }}/{{ ansible_distribution_version }}/prod"
        suites: insiders-fast
        components: main
        signed_by: "{{ redhat_aro_microsoft_legacy_signing_key_path }}"

    - name: Remove old-style "insiders fast" apt repository for Ubuntu
      ansible.builtin.file:
        path: "/etc/apt/sources.list.d/microsoft-{{ ansible_distribution | lower }}-{{ ansible_distribution_release }}-insiders-fast.list"
        state: absent

    - name: Add Microsoft's apt repository for Edge browser
      ansible.builtin.deb822_repository:
        name: microsoft-edge
        architectures: "{{ dpkg_architecture }}"
        uris: https://packages.microsoft.com/repos/edge
        suites: stable
        components: main
        signed_by: "{{ redhat_aro_microsoft_legacy_signing_key_path }}"

    - name: Remove old-style apt repository for Edge browser
      ansible.builtin.file:
        path: "/etc/apt/sources.list.d/microsoft-edge.list"
        state: absent

    - name: Install required packages for Microsoft Intune compliance
      ansible.builtin.apt:
        name:
          - intune-portal
          - microsoft-edge-stable
          - microsoft-identity-broker
        update_cache: true

    - name: Installed required packages for YubiKey smart cards
      ansible.builtin.apt:
        name:
          - libnss3-tools
          - opensc
          - openssl
          - pcscd
          - yubikey-manager

    - name: Add Red Hat Kerberos policy for Microsoft Edge
      ansible.builtin.copy:
        src: edge/redhat-corp.json
        dest: /etc/opt/edge/policies/managed/
        mode: u=rw,g=r,o=r
        owner: root
        group: root

    - name: Install git-credential-manager
      ansible.builtin.include_role:
        name: git_credential_manager

- name: Add directory for user NSS database
  ansible.builtin.file:
    path: "{{ redhat_aro_nssdb_user_dir }}"
    state: directory
    mode: u=rwx,g=,o=

- name: Create a user NSS database
  ansible.builtin.command:
    cmd: "modutil -force -dbdir sql:{{ redhat_aro_nssdb_user_dir }} -create"
    creates: "{{ redhat_aro_nssdb_user_dir }}/*.db"

- name: List smart card module in user NSS database
  ansible.builtin.command:
    cmd: "modutil -force -dbdir sql:{{ redhat_aro_nssdb_user_dir }} -list '{{ redhat_aro_nssdb_opensc_module_name }}'"
  register: redhat_aro_nssdb_opensc_module
  changed_when: false
  failed_when:
    - redhat_aro_nssdb_opensc_module.rc != 0
    # 29 : Module not found in database
    - redhat_aro_nssdb_opensc_module.rc != 29

- name: Create smart card module in user NSS database  # noqa: no-changed-when
  ansible.builtin.command:
    cmd: >
      modutil -force -dbdir sql:{{ redhat_aro_nssdb_user_dir }}
      -add '{{ redhat_aro_nssdb_opensc_module_name }}'
      -libfile /usr/lib/{{ dpkg_host_multiarch }}/pkcs11/opensc-pkcs11.so
  when: redhat_aro_nssdb_opensc_module.rc != 0
