---
- name: Begin Microsoft Intune configuration
  become: true
  block:

    # Note: Microsoft Intune also requires the operating system be
    #       installed on an encrypted volume but that's beyond the
    #       scope of this playbook.

    - name: Add pwquality PAM module
      ansible.builtin.apt:
        name: libpam-pwquality

    - name: Configure pwquality to meet Microsoft Intune requirements
      community.general.pamd:
        name: common-password
        type: password
        control: requisite
        module_path: pam_pwquality.so
        module_arguments:
          - minlen=12
          - dcredit=-1
          - ucredit=-1
          - lcredit=-1
          - ocredit=-1
        state: args_present

    - name: Add Microsoft's apt main repository for Ubuntu
      ansible.builtin.apt_repository:
        repo: >
          deb [arch={{ dpkg_architecture }} signed-by={{ redhat_aro_microsoft_legacy_signing_key_path }}]
          https://packages.microsoft.com/{{ ansible_distribution | lower }}/{{ ansible_distribution_version }}/prod
          {{ ansible_distribution_release }} main
        filename: "microsoft-{{ ansible_distribution | lower }}-{{ ansible_distribution_release }}-prod"

    - name: Add Microsoft's "insiders fast" apt repository for Ubuntu
      ansible.builtin.apt_repository:
        repo: >
          deb [arch={{ dpkg_architecture }} signed-by={{ redhat_aro_microsoft_legacy_signing_key_path }}]
          https://packages.microsoft.com/{{ ansible_distribution | lower }}/{{ ansible_distribution_version }}/prod
          insiders-fast main
        filename: "microsoft-{{ ansible_distribution | lower }}-{{ ansible_distribution_release }}-insiders-fast"

    - name: Add Microsoft's apt repository for Edge browser
      ansible.builtin.apt_repository:
        repo: >
          deb [arch={{ dpkg_architecture }} signed-by={{ redhat_aro_microsoft_legacy_signing_key_path }}]
          https://packages.microsoft.com/repos/edge stable main
        filename: "microsoft-edge"

    - name: Install required packages for Microsoft Intune compliance
      ansible.builtin.apt:
        name:
          - intune-portal
          - microsoft-edge-stable
          - microsoft-identity-broker

    - name: Installed required packages for YubiKey smart cards
      ansible.builtin.apt:
        name:
          - libnss3-tools
          - opensc
          - openssl
          - pcscd
          - yubikey-manager

    - name: Add Red Hat Kerberos policy for Microsoft Edge
      ansible.builtin.copy:
        src: edge/redhat-corp.json
        dest: /etc/opt/edge/policies/managed/
        mode: u=rw,g=r,o=r
        owner: root
        group: root

    - name: Install git-credential-manager
      ansible.builtin.include_role:
        name: git_credential_manager

- name: Add directory for user NSS database
  ansible.builtin.file:
    path: "{{ redhat_aro_nssdb_user_dir }}"
    state: directory
    mode: u=rwx,g=,o=

- name: Create a user NSS database
  ansible.builtin.command:
    cmd: "modutil -force -dbdir sql:{{ redhat_aro_nssdb_user_dir }} -create"
    creates: "{{ redhat_aro_nssdb_user_dir }}/*.db"

- name: List smart card module in user NSS database
  ansible.builtin.command:
    cmd: "modutil -force -dbdir sql:{{ redhat_aro_nssdb_user_dir }} -list '{{ redhat_aro_nssdb_opensc_module_name }}'"
  register: redhat_aro_nssdb_opensc_module
  changed_when: false
  failed_when:
    - redhat_aro_nssdb_opensc_module.rc != 0
    # 29 : Module not found in database
    - redhat_aro_nssdb_opensc_module.rc != 29

- name: Create smart card module in user NSS database  # noqa: no-changed-when
  ansible.builtin.command:
    cmd: >
      modutil -force -dbdir sql:{{ redhat_aro_nssdb_user_dir }}
      -add '{{ redhat_aro_nssdb_opensc_module_name }}'
      -libfile /usr/lib/{{ dpkg_host_multiarch }}/pkcs11/opensc-pkcs11.so
  when: redhat_aro_nssdb_opensc_module.rc != 0
