---
- name: Add user to "input" group
  user:
    name: "{{ ansible_user_id }}"
    groups: input
    append: yes
  become: yes

- name: Clone retrOSMCmk2 repo for RetroPie installer
  git:
    repo: https://github.com/hissingshark/retrOSMCmk2.git
    dest: "{{ ansible_user_dir }}/retrOSMCmk2"
