---
- block:

  - name: Increment the passphrase retry count
    set_fact:
      retry_count: "{{ 0 if retry_count is undefined else retry_count | int + 1 }}"

  - name: Prompt for secret GPG key passphrase
    pause:
      prompt: |

        Please enter the passphrase to export the OpenPGP secret key:
        "{{ item.uid }}"
        {{ item.keylen }}-bit {{ item.keyalg }} key, ID {{ item.keyid }},
        created {{ "%x" | strftime(item.date) }}
      echo: False
    register: gpg_secret_key_passphrase
    no_log: True

  - name: Use the passphrase to export the secret GPG key
    command:
      argv:
        - gpg2
        - --export-secret-keys
        - --armor
        - --batch
        - --pinentry-mode
        - loopback
        - --passphrase
        - "{{ gpg_secret_key_passphrase.user_input }}"
        - "{{ item.keyid }}"
    register: gpg_secret_key
    delegate_to: localhost
    changed_when: False
    run_once: True
    no_log: True

  rescue:

  - fail:
      msg: Unknown error when exporting secret key
    when: "'Bad passphrase' not in gpg_secret_key.stderr"

  - fail:
      msg: Maximum retries of secret key export reached
    when: retry_count | int == 3

  - include_tasks: export_secret_key.yml
