---
- name: Add packages for secrets
  apt:
    name:
    - gnupg2
    - pass
  become: yes

- name: Collect existing GPG keys
  command: "gpg2 --list-secret-keys --with-colons"
  register: gpg_colon_output

- name: Process GPG key data
  set_fact:
    gpg_remote_key_ids: |
      {% set result = [] %}
      {% for line in gpg_colon_output.stdout_lines %}
      {%   set fields = line.split(':') %}
      {%   if fields[0] == 'sec' %}
      {%     set _ = result.append(fields[4]) %}
      {%   endif %}
      {% endfor %}
      {{ result }}

- name: Collect local GPG keys to transfer
  command: "gpg2 --list-secret-keys --with-colons {{ gpg_key_email }}"
  register: gpg_colon_output
  delegate_to: localhost
  changed_when: False
  run_once: True

- name: Process GPG key data
  set_fact:
    gpg_secret_key_attrs: |
      {% set result = [] %}
      {% set algnames = {1: 'RSA'} %}
      {% for line in gpg_colon_output.stdout_lines %}
      {%   set fields = line.split(':') %}
      {%   if fields[0] == 'sec' %}
      {%     set _ = result.append({}) %}
      {%     set keyalg = algnames.get(fields[3], 'Unknown') %}
      {%     set _ = result[-1].__setitem__('keylen', fields[2]) %}
      {%     set _ = result[-1].__setitem__('keyalg', keyalg) %}
      {%     set _ = result[-1].__setitem__('keyid', fields[4]) %}
      {%     set _ = result[-1].__setitem__('date', fields[5]) %}
      {%   elif fields[0] == 'uid' %}
      {%     set _ = result[-1].__setitem__('uid', fields[9]) %}
      {%   endif %}
      {% endfor %}
      {{ result }}
  run_once: True

- name: Transfer each GPG key
  include_tasks: transfer_gpg_key.yml
  when: item.keyid not in gpg_remote_key_ids
  loop: "{{ gpg_secret_key_attrs }}"

- name: Export GPG ownertrust values
  command: "gpg2 --export-ownertrust"
  register: gpg_ownertrust
  delegate_to: localhost
  changed_when: False
  run_once: True

- name: Import GPG ownertrust values
  command:
  args:
    cmd: "gpg2 --import-ownertrust"
    stdin: "{{ gpg_ownertrust.stdout }}"

- name: Transfer SSH keys
  copy:
    src: "{{ item }}"
    dest: "{{ ansible_user_dir }}/.ssh/"
    mode: preserve
  with_fileglob: "~/.ssh/id_*"

- name: Clone password store repository
  git:
    repo: "{{ password_store_git_repo }}"
    dest: "{{ ansible_user_dir }}/.password-store"
