---
- name: Add the default Go toolchain
  apt:
    name:
    - golang-go
    - go-bindata
  become: true

- name: Create GOPATH directory
  file:
    path: "{{ golang_path }}"
    state: directory

# Do not overwrite the file since GOROOT may have been
# manually changed to a different Go toolchain version.
- name: Add GOPATH and GOROOT environment variables
  template:
    src: golang.j2
    dest: "{{ bash_aliases_dir }}/golang"
    force: no

- name: Query latest golangci-lint release assets
  uri:
    url: "https://api.github.com/repos/golangci/golangci-lint/releases/latest"
    headers:
      Accept: "application/vnd.github+json"
  register: golangci_lint_latest_release

- name: Find deb package amongst release assets
  set_fact:
    golangci_lint_release_asset: "{{ item }}"
  when: item.name.endswith(dpkg_architecture + ".deb")
  loop: "{{ golangci_lint_latest_release.json.assets }}"
  no_log: true  # Avoid spewing a bunch of JSON

- assert:
    that: golangci_lint_release_asset is defined
    success_msg: "Installing {{ golangci_lint_release_asset.name }}"
    fail_msg: "No package available for golangci-lint"

- name: Install deb package
  apt:
    deb: "{{ golangci_lint_release_asset.browser_download_url }}"
  become: yes

- name: Clone vim-go as a vim package
  git:
    repo: https://github.com/fatih/vim-go.git
    dest: "{{ ansible_user_dir }}/.vim/pack/plugins/start/vim-go"

- name: Install additional Go binaries to support vim-go
  command: vim -e "+GoInstallBinaries" "+q"
