---
- name: Copy advancedsettings.xml for Kodi
  template:
    src: "advancedsettings.xml.j2"
    dest: "{{ kodi_userdata_path }}/advancedsettings.xml"
  notify: Restart Kodi

- import_role:
    name: nginx_revproxy
  vars:
    nginx_revproxy_name: kodi
    nginx_revproxy_port: "{{ kodi_webserver_port }}"
  when: kodi_webserver
