---
- name: Begin usbip client configuration
  become: true
  block:

    - name: Add usbip package
      ansible.builtin.apt:
        name:
          - usbip
      when: ansible_distribution == 'Debian'

    - name: Add linux-tools-common package
      ansible.builtin.apt:
        name:
          - linux-tools-common
      when: ansible_distribution == 'Ubuntu'

    - name: Load the vhci_hcd kernel module
      community.general.modprobe:
        name: vhci_hcd
        state: present
        persistent: present
