---
dependencies:
  - role: common_user
  - role: git_dev
  - role: google_cloud_sdk
  - role: mozilla_firefox
    vars:
      mozilla_firefox_preferences:
        network.negotiate-auth.trusted-uris: .redhat.com
        # Deprecated; keep until Red Hat restricts VPN access.
        # https://kb.mozillazine.org/Network.proxy.autoconfig_url
        network.proxy.autoconfig_url: "{{ redhat_proxy_autoconfig_url }}"
        # Use Web Proxy Auto-Discovery Protocol (WPAD)
        # https://kb.mozillazine.org/Network.proxy.type
        network.proxy.type: 4
  - role: secrets
  - role: tmux
