includedir /etc/krb5.conf.d/

[libdefaults]
  default_realm = IPA.REDHAT.COM
  dns_canonicalize_hostname = false
  dns_lookup_kdc = false
  dns_lookup_realm = false
  forwardable = true
  renew_lifetime = 7d
  ticket_lifetime = 24h
  udp_preference_limit = 0

[realms]
    IPA.REDHAT.COM = {
       kdc = https://csb.home.arpa/kdc
       kpasswd_server = https://csb.home.arpa/kdc
    }
