---
common_system_base_packages:
  - apt-file
  - bash-completion
  - bind9-dnsutils
  - ca-certificates
  - command-not-found
  - htop
  - lsof
  - man-db
  - rsync
  - usbutils

common_system_certificate_authority_file: "/usr/local/share/ca-certificates/{{ local_domain_name }}.crt"
